########################################################
# Dockerfile to demonstrate the behaviour of CMD
########################################################
# Build from base image busybox:latest
FROM busybox:latest
# Author: Nana
MAINTAINER Nana <nraythz@gmail.com>
# Set command for CMD
CMD ["echo", "Dockerfile CMD demo"] 
